// Generated by CoffeeScript 2.6.1
var SimpleNodeA;

SimpleNodeA = class SimpleNodeA {
  constructor(node, data, ns) {
    this.node = node;
    this.data = data;
    this.ns = ns;
  }

  refresh() {
    // aida-220, aida-221
    if (this.data.value.value) {
      return this.node.text(this.data.value.value);
    }
  }

};

export {
  SimpleNodeA
};
