// Generated by CoffeeScript 2.6.1
var IbmTranscript;

IbmTranscript = class IbmTranscript {
  constructor(w) {
    this.w = w;
  }

  parsex(text) {
    var data, i, j, len, len1, o, ref, ref1, that, x, y;
    that = this;
    o = JSON.parse(text);
    data = [];
    ref = o.results;
    for (i = 0, len = ref.length; i < len; i++) {
      x = ref[i];
      ref1 = x.alternatives[0].timestamps;
      for (j = 0, len1 = ref1.length; j < len1; j++) {
        y = ref1[j];
        console.log(y);
        data.push([y[1], y[2], y[0]]);
      }
    }
    that.w.add_timestamps2(data);
    $('#browse_b').html('working...');
    return ldc_annotate.add_callback(function() {
      $('.Root').show();
      return $('#browse_b').hide();
    });
  }

  parse(text) {
    var data, i, len, o, that, x, y;
    that = this;
    o = text.split("\n");
    data = [];
    for (i = 0, len = o.length; i < len; i++) {
      x = o[i];
      // console.log x
      y = x.split("\t");
      if (y[0].match(/;/)) {
        continue;
      }
      if (y[7]) {
        data.push([y[2], y[3], y[7]]);
      }
    }
    that.w.add_timestamps2(data);
    $('#browse_b').html('working...');
    return ldc_annotate.add_callback(function() {
      $('.Root').show();
      return $('#browse_b').hide();
    });
  }

};

export {
  IbmTranscript
};
