// Generated by CoffeeScript 2.6.1
var ParseA;

ParseA = class ParseA {
  constructor(name) {
    this.name = name;
  }

  round_to_3_places(num) {
    return Math.round(num * 1000) / 1000;
  }

  parse(raw) {
    var header, info, length, sample_rate;
    header = new DataView((new Int8Array(raw)).buffer);
    length = header.getInt32(40, true) / header.getInt32(28, true);
    length = this.round_to_3_places(length);
    sample_rate = header.getInt32(24, true);
    console.log(`found length ${length}`);
    info = {
      duration: length,
      sample_rate: sample_rate
    };
    return info;
  }

};

export {
  ParseA
};
