// Generated by CoffeeScript 2.6.1
var create_component;

import LabelC from 'class_defs/features/label_c.svelte';

import RadioC from 'class_defs/features/radio_c.svelte';

import CheckC from 'class_defs/features/check_c.svelte';

import MenuC from 'class_defs/features/menu_c.svelte';

import EntryC from 'class_defs/features/entry_c.svelte';

import TextareaC from 'class_defs/features/textarea_c.svelte';

import MegaMenuC from 'class_defs/features/mega_menu_c.svelte';

create_component = function(node, data) {
  var h;
  if (!data.componentc) {
    h = data.component;
    if (h) {
      if (data.obj) {
        h.initial_objects = data.obj.initial_objects;
      }
      if (node.hasClass('Label')) {
        data.componentc = new LabelC({
          target: node[0],
          props: h
        });
      }
      if (node.hasClass('Radio')) {
        h.data = data;
        data.componentc = new RadioC({
          target: node[0],
          props: h
        });
      }
      if (node.hasClass('Checkbox')) {
        h.data = data;
        data.componentc = new CheckC({
          target: node[0],
          props: h
        });
      }
      if (node.hasClass('Menu')) {
        node.addClass('MenuC');
        h.data = data;
        data.componentc = new MenuC({
          target: node[0],
          props: h
        });
      }
      if (node.hasClass('Entry')) {
        h.data = data;
        data.componentc = new EntryC({
          target: node[0],
          props: h
        });
      }
      if (node.hasClass('Textarea')) {
        h.data = data;
        data.componentc = new TextareaC({
          target: node[0],
          props: h
        });
      }
      if (node.hasClass('MegaMenu')) {
        h.data = data;
        data.componentc = new MegaMenuC({
          target: node[0],
          props: h
        });
      }
      if (node.hasClass('Set')) {
        h.data = data;
        return data.componentc = new MenuC({
          target: node[0],
          props: h
        });
      }
    }
  }
};

export {
  create_component
};
