// Generated by CoffeeScript 2.6.1
var set_obj_helper;

set_obj_helper = function(f, node, data, h, ns) {
  var a, name;
  if (f === 'refresh') {
    a = node.attr('class').split(' ');
    if (a[0] === 'virtual') {
      name = a[2];
      if (name === '') {
        name = a[1];
      }
    } else {
      name = data.meta.name;
    }
  } else {
    name = data.meta.name;
  }
  if (h[name]) {
    if (!data.obj) {
      return data.obj = new h[name](node, data, ns);
    }
  }
};

export {
  set_obj_helper
};
