// Generated by CoffeeScript 2.6.1
var SectionList;

import {
  Keyboard
} from '../../work/keyboard';

SectionList = class SectionList {
  constructor(node, data, ns) {
    this.node = node;
    this.data = data;
    this.ns = ns;
  }

  logic() {
    // return this.ns.segment_list_f('segments', that);
  }








  // alert "sections #{y.join(',')}"





};

export {
  SectionList
};
