// Generated by CoffeeScript 2.6.1
var Speaker, last_speaker_used, setspeakerf;

import {
  Keyboard
} from '../../work/keyboard';


Speaker = class Speaker {
  constructor(node, data, ns) {
    this.node = node;
    this.data = data;
    this.ns = ns;
  }

  get_last_speaker_used() {
    return last_speaker_used;
  }

};

export {
  Speaker
};
