// Generated by CoffeeScript 2.6.1
var Audio, audio_loop;

audio_loop = function(t) {
  ldc_source.play_callback(t);
  ldc_source.waveform_callback();
  return requestAnimationFrame(audio_loop);
};

if (!window.ldc) {
  window.ldc = {};
}

if (!window.ldc.vars) {
  window.ldc.vars = {};
}

window.ldc.waveforms = [];

Audio = class Audio {
  constructor() {}

  web_audio_init() {
    var e, f, vars;
    if (this.audio_context) {
      return;
    }
    try {
      window.AudioContext = window.AudioContext || window.webkitAudioContext;
      vars = window.ldc.vars;
      if (!vars.audio_context_opts) {
        vars.audio_context_opts = {};
      }
      this.audio_context = new AudioContext(vars.audio_context_opts);
      vars.audio_context = this.audio_context;
      ldc_source.set_audio_context();
      console.log(`CONTEXT ${this.audio_context.state}`);
      // web_audio = true
      f = window.requestAnimationFrame || window.webkitRequestAnimationFrame;
      if (!f) {
        f = function(callback) {
          return window.setTimeout(callback, 1000 / 60);
        };
      }
      window.requestAnimationFrame = f;
    } catch (error) {
      e = error;
      alert('Web Audio API is not supported in this browser');
      console.log(e);
      return;
    }
    return requestAnimationFrame(audio_loop);
  }

};

export {
  // that.stopRecording = ->
  // that.startRecording = ->

  // ).catch (err) ->
  //     console.log 'getUserMedia error: ' + err.name, err
  // stream_helper1: (stream, record) ->
  Audio
};
