// Generated by CoffeeScript 2.6.1
import 'ace-builds';

import "ace-builds/webpack-resolver";

export var ldc_kit_types = (function() {
  return {
    //this code runs when viewing the kit types index page
    init_index: function() {
      $('.display').dataTable({
        sPaginationType: "full_numbers",
        bJQueryUI: true
      });
      return $('.delete_kt').on('click', function() {
        return ldc_lui.display_alert('error', 'Contact the web team if you need to delete a kit type.');
      });
    },
    //initialize helper popover
    // $('#kit_type_coref_groups').popover();
    init_show: function() {
      var callback, editor;
      $(document).on('change', '.features', function() {
        return $(this).addClass('features_modified');
      });
      editor = ace.edit('editor', {
        maxLines: 50,
        minLines: 10,
        value: $('.constraints2').val(),
        mode: "ace/mode/yaml"
      });
      callback = function(e) {
        console.log('changing');
        return console.log(e);
      };
      return editor.getSession().on('change', function() {
        return $('.constraints2').val(editor.getValue());
      });
    }
  };
})();
