// Generated by CoffeeScript 2.6.1
import {
  Browser
} from './browser';

export var ldc_tasks = (function() {
  var add_selection_listeners;
  //function that adds listeners to select all and none of the checkboxes on the page
  add_selection_listeners = function() {
    $('#select_all').on('click', function() {
      return $('input[type="checkbox"]').attr('checked', 'checked');
    });
    return $('#select_none').on('click', function() {
      return $('input[type="checkbox"]').removeAttr('checked');
    });
  };
  return {
    init_edit: function() {},
    //function that runs when loading the show page
    init_show: function() {
      var size;
      $('#task_members, #other_users, #counts').dataTable({
        paging: false,
        scrollY: '400px',
        scrollCollapse: true
      });
      $('.bucket').text("no bucket found");
      // browser = new Browser('#main');
      // browser.init()
      // browser.get_bucket_size()
      size = $('.bucket').data('bucket-size');
      return $('.bucket').html(`<div>found ${size} files in bucket</div>`);
    },
    //function that runs when loading the tasks index page
    init_index: function() {
      return $('#tasks').dataTable({
        paging: false,
        scrollY: '400px',
        scrollCollapse: true
      });
    },
    //function that runs when loading the kit generation preview page
    init_kit_generation_preview: function() {
      //add select all / select none functionality
      return add_selection_listeners();
    },
    //function that runs when loading the process kits preview page
    init_process_kits_preview: function() {
      //add select all / select none functionality
      return add_selection_listeners();
    },
    ds_modal_listener: function() {
      return $('.data_set_modal').on('click', function() {
        $('#edit_ds').addClass('open');
        return $("body").addClass("modal-open");
      });
    },
    reset_modal_listener: function() {
      return $('#reset_tool_link').on('click', function() {
        $('#reset_tool').addClass('open');
        return $("body").addClass("modal-open");
      });
    },
    order_listeners: function() {
      if ($('#task_kit_type_attributes_constraints_order_orderly').prop('checked')) {
        $('.repeating').hide();
      }
      $('body').on('click', '#task_kit_type_attributes_constraints_order_orderly', function(e) {
        $('#task_kit_type_attributes_constraints_repeating').prop('checked', false);
        return $('.repeating').hide();
      });
      return $('body').on('click', '#task_kit_type_attributes_constraints_order_random', function(e) {
        return $('.repeating').show();
      });
    }
  };
})();
